config/routes.rb
Rails.application.routes.draw do
# resources :wi_offline_msgs
  resources :usersettings
  resources :userprofiles
  resources :userpicks
  resources :usernotes
  resources :userdata
  resources :tokens
  resources :terrains
  resources :spawn_points
  resources :regionwindlights
  resources :regionsettings
  resources :regions
  resources :regionextras
  resources :regionenvironments
  resources :regionbans
  resources :profile_settings
  resources :profile_picks
  resources :profile_notes
  resources :profile_classifieds
  resources :profiles
  resources :primshapes
  resources :prims
  resources :primitems
  resources :os_groups_roles
  resources :os_groups_rolememberships
  resources :os_groups_principals
  resources :os_groups_notices
  resources :os_groups_memberships
  resources :os_groups_invites
  resources :os_groups_groups
  resources :migrations
  resources :landaccesslists
  resources :lands
  resources :inventoryitems
  resources :inventoryfolders
  resources :im_offlines
  resources :hg_traveling_data
  resources :estatebans
  resources :estate_users
  resources :estate_settings
  resources :estate_maps
  resources :estate_managers
  resources :estate_groups
  resources :classifieds
  resources :bakedterrains
  resources :auths
  resources :assets
  resources :user_accounts
  resources :presences
  resources :grid_users
  resources :friends
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/presence.rb
class Presence < ApplicationRecord
  self.table_name = "presence"
  
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.all
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new
  end

  # GET /presences/1/edit
  def edit
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)

    respond_to do |format|
      if @presence.save
        format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    respond_to do |format|
      format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:UserID, :RegionID, :SessionID, :SecureSessionID, :LastSeen)
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<%= form_for(presence) do |f| %>
  <% if presence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presence.errors.count, "error") %> prohibited this presence from being saved:</h2>

      <ul>
      <% presence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :UserID %>
    <%= f.text_field :UserID %>
  </div>

  <div class="field">
    <%= f.label :RegionID %>
    <%= f.text_field :RegionID %>
  </div>

  <div class="field">
    <%= f.label :SessionID %>
    <%= f.text_field :SessionID %>
  </div>

  <div class="field">
    <%= f.label :SecureSessionID %>
    <%= f.text_field :SecureSessionID %>
  </div>

  <div class="field">
    <%= f.label :LastSeen %>
    <%= f.datetime_select :LastSeen %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presences/edit.html.erb
<h1>Editing Presence</h1>

<%= render 'form', presence: @presence %>

<%= link_to 'Show', @presence %> |
<%= link_to 'Back', presences_path %>

app/views/presences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presences</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Regionid</th>
      <th>Sessionid</th>
      <th>Securesessionid</th>
      <th>Lastseen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presences.each do |presence| %>
      <tr>
        <td><%= presence.UserID %></td>
        <td><%= presence.RegionID %></td>
        <td><%= presence.SessionID %></td>
        <td><%= presence.SecureSessionID %></td>
        <td><%= presence.LastSeen %></td>
        <td><%= link_to 'Show', presence %></td>
        <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
        <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presence', new_presence_path %>

app/views/presences/new.html.erb
<h1>New Presence</h1>

<%= render 'form', presence: @presence %>

<%= link_to 'Back', presences_path %>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @presence.UserID %>
</p>

<p>
  <strong>Regionid:</strong>
  <%= @presence.RegionID %>
</p>

<p>
  <strong>Sessionid:</strong>
  <%= @presence.SessionID %>
</p>

<p>
  <strong>Securesessionid:</strong>
  <%= @presence.SecureSessionID %>
</p>

<p>
  <strong>Lastseen:</strong>
  <%= @presence.LastSeen %>
</p>

<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>