config/routes.rb
Rails.application.routes.draw do
# resources :wi_offline_msgs
  resources :usersettings
  resources :userprofiles
  resources :userpicks
  resources :usernotes
  resources :userdata
  resources :tokens
  resources :terrains
  resources :spawn_points
  resources :regionwindlights
  resources :regionsettings
  resources :regions
  resources :regionextras
  resources :regionenvironments
  resources :regionbans
  resources :profile_settings
  resources :profile_picks
  resources :profile_notes
  resources :profile_classifieds
  resources :profiles
  resources :primshapes
  resources :prims
  resources :primitems
  resources :os_groups_roles
  resources :os_groups_rolememberships
  resources :os_groups_principals
  resources :os_groups_notices
  resources :os_groups_memberships
  resources :os_groups_invites
  resources :os_groups_groups
  resources :migrations
  resources :landaccesslists
  resources :lands
  resources :inventoryitems
  resources :inventoryfolders
  resources :im_offlines
  resources :hg_traveling_data
  resources :estatebans
  resources :estate_users
  resources :estate_settings
  resources :estate_maps
  resources :estate_managers
  resources :estate_groups
  resources :classifieds
  resources :bakedterrains
  resources :auths
  resources :assets
  resources :user_accounts
  resources :presences
  resources :grid_users
  resources :friends
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/primitem.rb
# == Schema Information
#
# Table name: primitems
#
#  invType             :integer
#  assetType           :integer
#  name                :string(255)
#  description         :string(255)
#  creationDate        :integer
#  nextPermissions     :integer
#  currentPermissions  :integer
#  basePermissions     :integer
#  everyonePermissions :integer
#  groupPermissions    :integer
#  flags               :integer          default("0"), not null
#  itemID              :string(36)       default(""), not null, primary key
#  primID              :string(36)
#  assetID             :string(36)
#  parentFolderID      :string(36)
#  CreatorID           :string(255)      default(""), not null
#  ownerID             :string(36)
#  groupID             :string(36)
#  lastOwnerID         :string(36)
#

class Primitem < ApplicationRecord
end

app/controllers/primitems_controller.rb
class PrimitemsController < ApplicationController
  before_action :set_primitem, only: [:show, :edit, :update, :destroy]

  # GET /primitems
  # GET /primitems.json
  def index
    @primitems = Primitem.all
  end

  # GET /primitems/1
  # GET /primitems/1.json
  def show
  end

  # GET /primitems/new
  def new
    @primitem = Primitem.new
  end

  # GET /primitems/1/edit
  def edit
  end

  # POST /primitems
  # POST /primitems.json
  def create
    @primitem = Primitem.new(primitem_params)

    respond_to do |format|
      if @primitem.save
        format.html { redirect_to @primitem, notice: 'Primitem was successfully created.' }
        format.json { render :show, status: :created, location: @primitem }
      else
        format.html { render :new }
        format.json { render json: @primitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primitems/1
  # PATCH/PUT /primitems/1.json
  def update
    respond_to do |format|
      if @primitem.update(primitem_params)
        format.html { redirect_to @primitem, notice: 'Primitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @primitem }
      else
        format.html { render :edit }
        format.json { render json: @primitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primitems/1
  # DELETE /primitems/1.json
  def destroy
    @primitem.destroy
    respond_to do |format|
      format.html { redirect_to primitems_url, notice: 'Primitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_primitem
      @primitem = Primitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def primitem_params
      params.require(:primitem).permit(:invType, :assetType, :name, :description, :creationDate, :nextPermissions, :currentPermissions, :basePermissions, :everyonePermissions, :groupPermissions, :flags, :primID, :assetID, :parentFolderID, :CreatorID, :ownerID, :groupID, :lastOwnerID)
    end
end

app/helpers/primitems_helper.rb
module PrimitemsHelper
end

app/views/primitems/_form.html.erb
<%= form_for(primitem) do |f| %>
  <% if primitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(primitem.errors.count, "error") %> prohibited this primitem from being saved:</h2>

      <ul>
      <% primitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invType %>
    <%= f.number_field :invType %>
  </div>

  <div class="field">
    <%= f.label :assetType %>
    <%= f.number_field :assetType %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :creationDate %>
    <%= f.text_field :creationDate %>
  </div>

  <div class="field">
    <%= f.label :nextPermissions %>
    <%= f.number_field :nextPermissions %>
  </div>

  <div class="field">
    <%= f.label :currentPermissions %>
    <%= f.number_field :currentPermissions %>
  </div>

  <div class="field">
    <%= f.label :basePermissions %>
    <%= f.number_field :basePermissions %>
  </div>

  <div class="field">
    <%= f.label :everyonePermissions %>
    <%= f.number_field :everyonePermissions %>
  </div>

  <div class="field">
    <%= f.label :groupPermissions %>
    <%= f.number_field :groupPermissions %>
  </div>

  <div class="field">
    <%= f.label :flags %>
    <%= f.number_field :flags %>
  </div>

  <div class="field">
    <%= f.label :primID %>
    <%= f.text_field :primID %>
  </div>

  <div class="field">
    <%= f.label :assetID %>
    <%= f.text_field :assetID %>
  </div>

  <div class="field">
    <%= f.label :parentFolderID %>
    <%= f.text_field :parentFolderID %>
  </div>

  <div class="field">
    <%= f.label :CreatorID %>
    <%= f.text_field :CreatorID %>
  </div>

  <div class="field">
    <%= f.label :ownerID %>
    <%= f.text_field :ownerID %>
  </div>

  <div class="field">
    <%= f.label :groupID %>
    <%= f.text_field :groupID %>
  </div>

  <div class="field">
    <%= f.label :lastOwnerID %>
    <%= f.text_field :lastOwnerID %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/primitems/edit.html.erb
<h1>Editing Primitem</h1>

<%= render 'form', primitem: @primitem %>

<%= link_to 'Show', @primitem %> |
<%= link_to 'Back', primitems_path %>

app/views/primitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Primitems</h1>

<table>
  <thead>
    <tr>
      <th>Invtype</th>
      <th>Assettype</th>
      <th>Name</th>
      <th>Description</th>
      <th>Creationdate</th>
      <th>Nextpermissions</th>
      <th>Currentpermissions</th>
      <th>Basepermissions</th>
      <th>Everyonepermissions</th>
      <th>Grouppermissions</th>
      <th>Flags</th>
      <th>Primid</th>
      <th>Assetid</th>
      <th>Parentfolderid</th>
      <th>Creatorid</th>
      <th>Ownerid</th>
      <th>Groupid</th>
      <th>Lastownerid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @primitems.each do |primitem| %>
      <tr>
        <td><%= primitem.invType %></td>
        <td><%= primitem.assetType %></td>
        <td><%= primitem.name %></td>
        <td><%= primitem.description %></td>
        <td><%= primitem.creationDate %></td>
        <td><%= primitem.nextPermissions %></td>
        <td><%= primitem.currentPermissions %></td>
        <td><%= primitem.basePermissions %></td>
        <td><%= primitem.everyonePermissions %></td>
        <td><%= primitem.groupPermissions %></td>
        <td><%= primitem.flags %></td>
        <td><%= primitem.primID %></td>
        <td><%= primitem.assetID %></td>
        <td><%= primitem.parentFolderID %></td>
        <td><%= primitem.CreatorID %></td>
        <td><%= primitem.ownerID %></td>
        <td><%= primitem.groupID %></td>
        <td><%= primitem.lastOwnerID %></td>
        <td><%= link_to 'Show', primitem %></td>
        <td><%= link_to 'Edit', edit_primitem_path(primitem) %></td>
        <td><%= link_to 'Destroy', primitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Primitem', new_primitem_path %>

app/views/primitems/new.html.erb
<h1>New Primitem</h1>

<%= render 'form', primitem: @primitem %>

<%= link_to 'Back', primitems_path %>

app/views/primitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invtype:</strong>
  <%= @primitem.invType %>
</p>

<p>
  <strong>Assettype:</strong>
  <%= @primitem.assetType %>
</p>

<p>
  <strong>Name:</strong>
  <%= @primitem.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @primitem.description %>
</p>

<p>
  <strong>Creationdate:</strong>
  <%= @primitem.creationDate %>
</p>

<p>
  <strong>Nextpermissions:</strong>
  <%= @primitem.nextPermissions %>
</p>

<p>
  <strong>Currentpermissions:</strong>
  <%= @primitem.currentPermissions %>
</p>

<p>
  <strong>Basepermissions:</strong>
  <%= @primitem.basePermissions %>
</p>

<p>
  <strong>Everyonepermissions:</strong>
  <%= @primitem.everyonePermissions %>
</p>

<p>
  <strong>Grouppermissions:</strong>
  <%= @primitem.groupPermissions %>
</p>

<p>
  <strong>Flags:</strong>
  <%= @primitem.flags %>
</p>

<p>
  <strong>Primid:</strong>
  <%= @primitem.primID %>
</p>

<p>
  <strong>Assetid:</strong>
  <%= @primitem.assetID %>
</p>

<p>
  <strong>Parentfolderid:</strong>
  <%= @primitem.parentFolderID %>
</p>

<p>
  <strong>Creatorid:</strong>
  <%= @primitem.CreatorID %>
</p>

<p>
  <strong>Ownerid:</strong>
  <%= @primitem.ownerID %>
</p>

<p>
  <strong>Groupid:</strong>
  <%= @primitem.groupID %>
</p>

<p>
  <strong>Lastownerid:</strong>
  <%= @primitem.lastOwnerID %>
</p>

<%= link_to 'Edit', edit_primitem_path(@primitem) %> |
<%= link_to 'Back', primitems_path %>