config/routes.rb
Rails.application.routes.draw do
# resources :wi_offline_msgs
  resources :usersettings
  resources :userprofiles
  resources :userpicks
  resources :usernotes
  resources :userdata
  resources :tokens
  resources :terrains
  resources :spawn_points
  resources :regionwindlights
  resources :regionsettings
  resources :regions
  resources :regionextras
  resources :regionenvironments
  resources :regionbans
  resources :profile_settings
  resources :profile_picks
  resources :profile_notes
  resources :profile_classifieds
  resources :profiles
  resources :primshapes
  resources :prims
  resources :primitems
  resources :os_groups_roles
  resources :os_groups_rolememberships
  resources :os_groups_principals
  resources :os_groups_notices
  resources :os_groups_memberships
  resources :os_groups_invites
  resources :os_groups_groups
  resources :migrations
  resources :landaccesslists
  resources :lands
  resources :inventoryitems
  resources :inventoryfolders
  resources :im_offlines
  resources :hg_traveling_data
  resources :estatebans
  resources :estate_users
  resources :estate_settings
  resources :estate_maps
  resources :estate_managers
  resources :estate_groups
  resources :classifieds
  resources :bakedterrains
  resources :auths
  resources :assets
  resources :user_accounts
  resources :presences
  resources :grid_users
  resources :friends
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estateban.rb
# == Schema Information
#
# Table name: estateban
#
#  EstateID         :integer          not null
#  bannedUUID       :string(36)       not null
#  bannedIp         :string(16)       not null
#  bannedIpHostMask :string(16)       not null
#  bannedNameMask   :string(64)
#

class Estateban < ApplicationRecord
  self.table_name = "estateban"
end

app/controllers/estatebans_controller.rb
class EstatebansController < ApplicationController
  before_action :set_estateban, only: [:show, :edit, :update, :destroy]

  # GET /estatebans
  # GET /estatebans.json
  def index
    @estatebans = Estateban.all
  end

  # GET /estatebans/1
  # GET /estatebans/1.json
  def show
  end

  # GET /estatebans/new
  def new
    @estateban = Estateban.new
  end

  # GET /estatebans/1/edit
  def edit
  end

  # POST /estatebans
  # POST /estatebans.json
  def create
    @estateban = Estateban.new(estateban_params)

    respond_to do |format|
      if @estateban.save
        format.html { redirect_to @estateban, notice: 'Estateban was successfully created.' }
        format.json { render :show, status: :created, location: @estateban }
      else
        format.html { render :new }
        format.json { render json: @estateban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estatebans/1
  # PATCH/PUT /estatebans/1.json
  def update
    respond_to do |format|
      if @estateban.update(estateban_params)
        format.html { redirect_to @estateban, notice: 'Estateban was successfully updated.' }
        format.json { render :show, status: :ok, location: @estateban }
      else
        format.html { render :edit }
        format.json { render json: @estateban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estatebans/1
  # DELETE /estatebans/1.json
  def destroy
    @estateban.destroy
    respond_to do |format|
      format.html { redirect_to estatebans_url, notice: 'Estateban was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estateban
      @estateban = Estateban.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estateban_params
      params.require(:estateban).permit(:EstateID, :bannedUUID, :bannedIp, :bannedIpHostMask, :bannedNameMask)
    end
end

app/helpers/estatebans_helper.rb
module EstatebansHelper
end

app/views/estatebans/_form.html.erb
<%= form_for(estateban) do |f| %>
  <% if estateban.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estateban.errors.count, "error") %> prohibited this estateban from being saved:</h2>

      <ul>
      <% estateban.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :EstateID %>
    <%= f.number_field :EstateID %>
  </div>

  <div class="field">
    <%= f.label :bannedUUID %>
    <%= f.text_field :bannedUUID %>
  </div>

  <div class="field">
    <%= f.label :bannedIp %>
    <%= f.text_field :bannedIp %>
  </div>

  <div class="field">
    <%= f.label :bannedIpHostMask %>
    <%= f.text_field :bannedIpHostMask %>
  </div>

  <div class="field">
    <%= f.label :bannedNameMask %>
    <%= f.text_field :bannedNameMask %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estatebans/edit.html.erb
<h1>Editing Estateban</h1>

<%= render 'form', estateban: @estateban %>

<%= link_to 'Show', @estateban %> |
<%= link_to 'Back', estatebans_path %>

app/views/estatebans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estatebans</h1>

<table>
  <thead>
    <tr>
      <th>Estateid</th>
      <th>Banneduuid</th>
      <th>Bannedip</th>
      <th>Bannediphostmask</th>
      <th>Bannednamemask</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estatebans.each do |estateban| %>
      <tr>
        <td><%= estateban.EstateID %></td>
        <td><%= estateban.bannedUUID %></td>
        <td><%= estateban.bannedIp %></td>
        <td><%= estateban.bannedIpHostMask %></td>
        <td><%= estateban.bannedNameMask %></td>
        <td><%= link_to 'Show', estateban %></td>
        <td><%= link_to 'Edit', edit_estateban_path(estateban) %></td>
        <td><%= link_to 'Destroy', estateban, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estateban', new_estateban_path %>

app/views/estatebans/new.html.erb
<h1>New Estateban</h1>

<%= render 'form', estateban: @estateban %>

<%= link_to 'Back', estatebans_path %>

app/views/estatebans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estateid:</strong>
  <%= @estateban.EstateID %>
</p>

<p>
  <strong>Banneduuid:</strong>
  <%= @estateban.bannedUUID %>
</p>

<p>
  <strong>Bannedip:</strong>
  <%= @estateban.bannedIp %>
</p>

<p>
  <strong>Bannediphostmask:</strong>
  <%= @estateban.bannedIpHostMask %>
</p>

<p>
  <strong>Bannednamemask:</strong>
  <%= @estateban.bannedNameMask %>
</p>

<%= link_to 'Edit', edit_estateban_path(@estateban) %> |
<%= link_to 'Back', estatebans_path %>