config/routes.rb
Rails.application.routes.draw do
# resources :wi_offline_msgs
  resources :usersettings
  resources :userprofiles
  resources :userpicks
  resources :usernotes
  resources :userdata
  resources :tokens
  resources :terrains
  resources :spawn_points
  resources :regionwindlights
  resources :regionsettings
  resources :regions
  resources :regionextras
  resources :regionenvironments
  resources :regionbans
  resources :profile_settings
  resources :profile_picks
  resources :profile_notes
  resources :profile_classifieds
  resources :profiles
  resources :primshapes
  resources :prims
  resources :primitems
  resources :os_groups_roles
  resources :os_groups_rolememberships
  resources :os_groups_principals
  resources :os_groups_notices
  resources :os_groups_memberships
  resources :os_groups_invites
  resources :os_groups_groups
  resources :migrations
  resources :landaccesslists
  resources :lands
  resources :inventoryitems
  resources :inventoryfolders
  resources :im_offlines
  resources :hg_traveling_data
  resources :estatebans
  resources :estate_users
  resources :estate_settings
  resources :estate_maps
  resources :estate_managers
  resources :estate_groups
  resources :classifieds
  resources :bakedterrains
  resources :auths
  resources :assets
  resources :user_accounts
  resources :presences
  resources :grid_users
  resources :friends
  resources :avatars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:PrincipalID, :Friend, :Flags, :Offered)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(friend) do |f| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PrincipalID %>
    <%= f.text_field :PrincipalID %>
  </div>

  <div class="field">
    <%= f.label :Friend %>
    <%= f.text_field :Friend %>
  </div>

  <div class="field">
    <%= f.label :Flags %>
    <%= f.text_field :Flags %>
  </div>

  <div class="field">
    <%= f.label :Offered %>
    <%= f.text_field :Offered %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends</h1>

<table>
  <thead>
    <tr>
      <th>Principalid</th>
      <th>Friend</th>
      <th>Flags</th>
      <th>Offered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.PrincipalID %></td>
        <td><%= friend.Friend %></td>
        <td><%= friend.Flags %></td>
        <td><%= friend.Offered %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Principalid:</strong>
  <%= @friend.PrincipalID %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friend.Friend %>
</p>

<p>
  <strong>Flags:</strong>
  <%= @friend.Flags %>
</p>

<p>
  <strong>Offered:</strong>
  <%= @friend.Offered %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>